import crypto from 'crypto';import {adminDb} from './firebase-admin';
const key=()=>{const raw=process.env.TOKEN_ENCRYPTION_KEY??'';return raw.length>=64?Buffer.from(raw,'hex').subarray(0,32):crypto.createHash('sha256').update(raw||'relay-development-key').digest()};
export function encrypt(value:string){const iv=crypto.randomBytes(12);const cipher=crypto.createCipheriv('aes-256-gcm',key(),iv);const encrypted=Buffer.concat([cipher.update(value,'utf8'),cipher.final()]);return `${iv.toString('base64')}.${cipher.getAuthTag().toString('base64')}.${encrypted.toString('base64')}`}
export function decrypt(value:string){const [iv,tag,payload]=value.split('.');const decipher=crypto.createDecipheriv('aes-256-gcm',key(),Buffer.from(iv,'base64'));decipher.setAuthTag(Buffer.from(tag,'base64'));return Buffer.concat([decipher.update(Buffer.from(payload,'base64')),decipher.final()]).toString('utf8')}
export async function getWhatsAppConnection(businessId:string){const snap=await adminDb.collection('whatsappConnections').doc(businessId).get();if(!snap.exists)return null;const data=snap.data()!;return {businessId,wabaId:data.wabaId,phoneNumberId:data.phoneNumberId,status:data.status,accessTokenConfigured:Boolean(data.accessTokenEncrypted),updatedAt:data.updatedAt}}
export async function saveWhatsAppConnection(value:{businessId:string;wabaId:string;phoneNumberId:string;accessToken:string}){const data={businessId:value.businessId,wabaId:value.wabaId,phoneNumberId:value.phoneNumberId,accessTokenEncrypted:encrypt(value.accessToken),status:'connected',updatedAt:new Date().toISOString()};await adminDb.collection('whatsappConnections').doc(value.businessId).set(data);return getWhatsAppConnection(value.businessId)}
export function verifyMetaSignature(raw:Buffer,signature:string|undefined){const secret=process.env.META_APP_SECRET;if(!secret||!signature?.startsWith('sha256='))return false;const expected=crypto.createHmac('sha256',secret).update(raw).digest('hex');const received=signature.slice(7);return received.length===expected.length&&crypto.timingSafeEqual(Buffer.from(received),Buffer.from(expected))}
export async function recordWebhook(messageId:string,payload:unknown){const ref=adminDb.collection('whatsappEvents').doc(messageId);return adminDb.runTransaction(async tx=>{const existing=await tx.get(ref);if(existing.exists)return false;tx.set(ref,{messageId,payload,receivedAt:new Date().toISOString(),processed:false});return true})}
export async function forwardToN8n(payload:unknown){const url=process.env.N8N_WHATSAPP_WEBHOOK_URL;if(!url)return false;const response=await fetch(url,{method:'POST',headers:{'content-type':'application/json','x-relay-webhook-secret':process.env.N8N_WEBHOOK_SECRET??''},body:JSON.stringify(payload)});return response.ok}
