import {Router} from 'express';
import {z} from 'zod';
import {requireRole, requireTenant} from '../middleware/auth';
import {campaignAudienceCounts, sendCampaign} from '../services/campaigns';
import {adminDb} from '../services/firebase-admin';

export const campaigns = Router();
campaigns.get('/businesses/:businessId/campaigns/push/audiences', requireTenant, async (req, res, next) => { try { return res.json({ success: true, data: await campaignAudienceCounts(req.businessId!) }); } catch (error) { return next(error); } });
campaigns.post('/businesses/:businessId/campaigns/push/audiences', requireTenant, requireRole('owner', 'admin'), async (req, res, next) => { try { const body = z.object({ name: z.string().trim().min(1).max(80), customerIds: z.array(z.string().min(1)).default([]) }).parse(req.body); const ref = adminDb.collection('pushAudiences').doc(); const data = { id: ref.id, businessId: req.businessId!, name: body.name, customerIds: [...new Set(body.customerIds)], createdAt: new Date().toISOString() }; await ref.set(data); return res.status(201).json({ success: true, data: { ...data, count: data.customerIds.length } }); } catch (error) { return next(error); } });
campaigns.get('/businesses/:businessId/campaigns/push', requireTenant, async (req, res, next) => { try { const snap = await adminDb.collection('campaigns').where('businessId', '==', req.businessId!).orderBy('createdAt', 'desc').limit(20).get(); return res.json({ success: true, data: snap.docs.map(doc => doc.data()) }); } catch (error) { return next(error); } });
campaigns.post('/businesses/:businessId/campaigns/push/send', requireTenant, requireRole('owner', 'admin'), async (req, res, next) => { try { const body = z.object({ segment: z.string().min(1), title: z.string().min(1).max(80), body: z.string().min(1).max(240), deepLink: z.string().url().optional(), inactiveDays: z.number().int().positive().optional(), ctaTitle: z.string().trim().max(30).optional(), ctaColor: z.string().regex(/^#[0-9a-fA-F]{6}$/).optional(), palette: z.enum(['ocean', 'forest', 'sunset', 'berry', 'midnight']).optional() }).parse(req.body); return res.status(201).json({ success: true, data: await sendCampaign({ ...body, businessId: req.businessId! }) }); } catch (error) { return next(error); } });
