import {Router} from 'express';import {z} from 'zod';import {AppError} from '../lib/errors';import {getStorefront} from '../services/firestore-commerce';import {adminDb} from '../services/firebase-admin';import {requireRole,requireTenant} from '../middleware/auth';
export const crm=Router();
const eventSchema=z.object({customerId:z.string().optional(),sessionId:z.string().optional(),channel:z.enum(['web','whatsapp','push','delivery']),type:z.string().min(1),payload:z.record(z.unknown()).default({})}).refine(v=>Boolean(v.customerId||v.sessionId),{message:'customerId or sessionId is required'});
const customerInput=z.object({name:z.string().min(1).max(120).trim(),email:z.string().email().optional().or(z.literal('')),phone:z.string().min(7).max(24).optional().or(z.literal('')),location:z.string().max(180).optional().default('')}).refine(value=>Boolean(value.email||value.phone),{message:'Email or phone is required'});
const customerPatch=z.object({name:z.string().min(1).max(120).trim().optional(),email:z.string().email().optional().or(z.literal('')),phone:z.string().min(7).max(24).optional().or(z.literal('')),location:z.string().max(180).optional(),pinnedNote:z.string().max(1000).optional(),categoryIds:z.array(z.string()).max(20).optional()});
const categoryInput=z.object({name:z.string().min(1).max(40).trim(),color:z.string().regex(/^#[0-9a-fA-F]{6}$/)});
const weekStart=(date=new Date())=>{const result=new Date(date);result.setHours(0,0,0,0);result.setDate(result.getDate()-((result.getDay()+6)%7));return result};
async function writeEvent(businessId:string,value:z.infer<typeof eventSchema>){const id=crypto.randomUUID();const event={id,businessId,...value,timestamp:new Date().toISOString()};await adminDb.collection('crmEvents').doc(id).create(event);if(value.customerId)await adminDb.collection('customers').doc(value.customerId).set({id:value.customerId,businessId,lastActivityAt:event.timestamp,updatedAt:event.timestamp},{merge:true});return event}
crm.post('/storefronts/:slug/events',async(req,res,next)=>{try{const store=await getStorefront(req.params.slug);if(!store||!store.published)return next(new AppError('NOT_FOUND','Storefront not found.',404));return res.status(202).json({success:true,data:await writeEvent(store.businessId,eventSchema.parse(req.body))})}catch(e){return next(new AppError('VALIDATION_ERROR',e instanceof Error?e.message:'Invalid CRM event'))}});
crm.get('/businesses/:businessId/customers',requireTenant,async(req,res,next)=>{try{const businessId=req.businessId!;const [customerSnap,orderSnap,eventSnap,categorySnap]=await Promise.all([adminDb.collection('customers').where('businessId','==',businessId).get(),adminDb.collection('orders').where('businessId','==',businessId).get(),adminDb.collection('crmEvents').where('businessId','==',businessId).get(),adminDb.collection('customerCategories').where('businessId','==',businessId).get()]);const events=eventSnap.docs.map(doc=>doc.data());const customers=customerSnap.docs.map(doc=>({id:doc.id,...doc.data()})) as any[];const orders=orderSnap.docs.map(doc=>doc.data()) as any[];const start=weekStart();const items=customers.map(customer=>{const paid=orders.filter(order=>order.paymentStatus==='paid'&&(order.customerId===customer.id||order.customer?.id===customer.id));const customerEvents=events.filter(event=>event.customerId===customer.id).sort((a,b)=>String(b.timestamp).localeCompare(String(a.timestamp)));const totalSpent=paid.reduce((sum,order)=>sum+Number(order.subtotal||order.total||0),0);return {...customer,totalSpent,paidOrderCount:paid.length,averageOrder:paid.length?totalSpent/paid.length:null,lastActivityAt:customerEvents[0]?.timestamp||customer.lastActivityAt||customer.createdAt||null,events:customerEvents.slice(0,100),walletBalance:Number(customer.walletBalance||0),loyaltyPoints:Number(customer.loyaltyPoints||0),categoryIds:Array.isArray(customer.categoryIds)?customer.categoryIds:[]}}).sort((a,b)=>String(b.lastActivityAt||'').localeCompare(String(a.lastActivityAt||'')));return res.json({success:true,data:{customers:items,categories:categorySnap.docs.map(doc=>({id:doc.id,...doc.data()})),totalCustomers:customers.length,newThisWeek:customers.filter(customer=>new Date(customer.createdAt||0)>=start).length}})}catch(e){return next(e)}});
crm.post('/businesses/:businessId/customers',requireTenant,requireRole('owner','admin'),async(req,res,next)=>{try{const value=customerInput.parse(req.body);const now=new Date().toISOString();const item={id:crypto.randomUUID(),businessId:req.businessId!,...value,categoryIds:[],walletBalance:0,loyaltyPoints:0,pinnedNote:'',createdAt:now,updatedAt:now};await adminDb.collection('customers').doc(item.id).set(item);return res.status(201).json({success:true,data:item})}catch(e){return next(new AppError('VALIDATION_ERROR',e instanceof Error?e.message:'Invalid customer'))}});
crm.patch('/customers/:id',requireTenant,requireRole('owner','admin'),async(req,res,next)=>{try{const id=String(req.params.id);const ref=adminDb.collection('customers').doc(id);const snap=await ref.get();if(!snap.exists||snap.get('businessId')!==req.businessId)return next(new AppError('NOT_FOUND','Customer not found.',404));const value=customerPatch.parse(req.body);await ref.update({...value,updatedAt:new Date().toISOString()});return res.json({success:true,data:{id,...snap.data(),...value}})}catch(e){return next(new AppError('VALIDATION_ERROR',e instanceof Error?e.message:'Invalid customer update'))}});
crm.get('/businesses/:businessId/customer-categories',requireTenant,async(req,res,next)=>{try{const snap=await adminDb.collection('customerCategories').where('businessId','==',req.businessId).get();return res.json({success:true,data:snap.docs.map(doc=>({id:doc.id,...doc.data()}))})}catch(e){return next(e)}});
crm.post('/businesses/:businessId/customer-categories',requireTenant,requireRole('owner','admin'),async(req,res,next)=>{try{const value=categoryInput.parse(req.body);const item={id:crypto.randomUUID(),businessId:req.businessId!,...value,createdAt:new Date().toISOString()};await adminDb.collection('customerCategories').doc(item.id).set(item);return res.status(201).json({success:true,data:item})}catch(e){return next(new AppError('VALIDATION_ERROR',e instanceof Error?e.message:'Invalid category'))}});
crm.patch('/customer-categories/:id',requireTenant,requireRole('owner','admin'),async(req,res,next)=>{try{const id=String(req.params.id);const ref=adminDb.collection('customerCategories').doc(id);const snap=await ref.get();if(!snap.exists||snap.get('businessId')!==req.businessId)return next(new AppError('NOT_FOUND','Category not found.',404));const value=categoryInput.partial().parse(req.body);await ref.update(value);return res.json({success:true,data:{id,...snap.data(),...value}})}catch(e){return next(new AppError('VALIDATION_ERROR',e instanceof Error?e.message:'Invalid category'))}});
crm.delete('/customer-categories/:id',requireTenant,requireRole('owner','admin'),async(req,res,next)=>{try{const id=String(req.params.id);const ref=adminDb.collection('customerCategories').doc(id);const snap=await ref.get();if(!snap.exists||snap.get('businessId')!==req.businessId)return next(new AppError('NOT_FOUND','Category not found.',404));const customers=await adminDb.collection('customers').where('businessId','==',req.businessId).where('categoryIds','array-contains',id).get();const batch=adminDb.batch();customers.docs.forEach(doc=>batch.update(doc.ref,{categoryIds:(doc.get('categoryIds')||[]).filter((categoryId:string)=>categoryId!==id)}));batch.delete(ref);await batch.commit();return res.json({success:true,data:{id,deleted:true}})}catch(e){return next(e)}});
crm.get('/businesses/:businessId/customers/:customerId/events',requireTenant,async(req,res,next)=>{try{const snap=await adminDb.collection('crmEvents').where('businessId','==',req.params.businessId).where('customerId','==',req.params.customerId).orderBy('timestamp','desc').limit(100).get();return res.json({success:true,data:snap.docs.map(d=>d.data())})}catch(e){return next(e)}});
