import {Router} from 'express';import {z} from 'zod';import {AppError} from '../lib/errors';import {requireRole,requireTenant} from '../middleware/auth';import {getStorefront} from '../services/firestore-commerce';import {quoteDelivery,saveZone,listZones,setOrderDelivery} from '../services/delivery';import {assignBatch,createBatch,listBatches} from '../services/delivery-batches';
export const delivery=Router();const zoneSchema=z.object({name:z.string().min(1),match:z.string().min(1),price:z.number().int().nonnegative(),currency:z.string().default('NGN'),timeframe:z.string().min(1),active:z.boolean().default(true)});
delivery.get('/businesses/:businessId/delivery-zones',requireTenant,async(req,res,next)=>{try{return res.json({success:true,data:await listZones(req.businessId!)})}catch(e){return next(e)}});
delivery.post('/businesses/:businessId/delivery-zones',requireTenant,requireRole('owner','admin'),async(req,res,next)=>{try{const data=zoneSchema.parse(req.body);const zone=await saveZone({id:crypto.randomUUID(),businessId:req.businessId!,...data});return res.status(201).json({success:true,data:zone})}catch(e){return next(new AppError('VALIDATION_ERROR',e instanceof Error?e.message:'Invalid delivery zone'))}});
delivery.post('/storefronts/:slug/delivery-quote',async(req,res,next)=>{try{const store=await getStorefront(String(req.params.slug));if(!store||!store.published)return next(new AppError('NOT_FOUND','Storefront not found.',404));const body=z.object({location:z.string().min(1),method:z.enum(['self_arranged','uber_direct','pickup'])}).parse(req.body);const quote=await quoteDelivery(store.businessId,body.location,body.method);if(!quote)return next(new AppError('DELIVERY_UNAVAILABLE','No delivery zone covers that location.',422));return res.json({success:true,data:quote})}catch(e){return next(e)}});
delivery.post('/orders/:orderId/delivery-method',requireTenant,requireRole('owner','admin'),async(req,res,next)=>{try{const body=z.object({method:z.enum(['self_arranged','uber_direct','pickup']),fee:z.number().int().nonnegative(),timeframe:z.string().min(1),zoneId:z.string().optional(),batchId:z.string().optional()}).parse(req.body);return res.json({success:true,data:await setOrderDelivery(String(req.params.orderId),body)})}catch(e){return next(e)}});
delivery.get('/businesses/:businessId/delivery-batches',requireTenant,async(req,res,next)=>{try{return res.json({success:true,data:await listBatches(req.businessId!)})}catch(e){return next(e)}});
delivery.post('/businesses/:businessId/delivery-batches',requireTenant,requireRole('owner','admin'),async(req,res,next)=>{try{const body=z.object({zoneId:z.string().min(1),name:z.string().min(1),cutoffAt:z.string().datetime(),dispatchAt:z.string().datetime()}).parse(req.body);return res.status(201).json({success:true,data:await createBatch({...body,businessId:req.businessId!})})}catch(e){return next(new AppError('VALIDATION_ERROR',e instanceof Error?e.message:'Invalid delivery batch'))}});
delivery.post('/orders/:orderId/delivery-batch',requireTenant,requireRole('owner','admin'),async(req,res,next)=>{try{const batchId=z.string().min(1).parse(req.body.batchId);return res.json({success:true,data:await assignBatch(String(req.params.orderId),req.businessId!,batchId)})}catch(e){return next(new AppError('BATCH_UNAVAILABLE',e instanceof Error?e.message:'Delivery batch unavailable',409))}});
