import {useQuery} from '@tanstack/react-query';
import {Activity,ArrowDownRight,ArrowUpRight,BarChart3,ChevronRight,Megaphone,Package,Users} from 'lucide-react';
import {useEffect,useMemo,useState} from 'react';
import {Link} from 'wouter';
import {auth} from '@/lib/firebase';

type Tab='overview'|'monthly'|'analytic';
type DashboardData={businessName:string;hero?:{overview?:number;weekly?:number;projected?:number;currency:string;comparison?:{value:number;period:string};weeklyComparison?:{value:number;period:string};analyticComparison?:{value:number;period:string}};revenueTrend?:Array<{label:string;value:number}>;weeklyActivity?:Array<{label:string;value:number}>;recentOrders?:Array<{id:string;customerName:string;relativeTime:string;itemCount:number;total:number;status:string}>;topMovers?:Array<{name:string;orders:number;revenue:number}>;needsAttention?:Array<{id:string;name:string;condition:string}>;target?:{value:number;period:string;reached:number};audience?:{total:number;active:number;newCustomers:number;inactive:number};topCategories?:Array<{name:string;share:number}>;ltv?:{value:number;trend:number}};

async function loadDashboard():Promise<DashboardData|null>{
  const businessId=typeof window!=='undefined'?(localStorage.getItem('relay_business_id')||import.meta.env.VITE_BUSINESS_ID):undefined;
  if(!businessId)return null;
  const token=await auth?.currentUser?.getIdToken();
  if(!token)return null;
  const response=await fetch(`${import.meta.env.VITE_API_URL||'http://localhost:4000'}/api/v1/businesses/${businessId}/dashboard`,{headers:{Authorization:`Bearer ${token}`,'x-business-id':businessId}});
  if(!response.ok)throw new Error('Dashboard data unavailable');
  const payload=await response.json();
  return payload.data as DashboardData;
}

const money=(value:number|undefined,currency='NGN')=>value===undefined?'—':new Intl.NumberFormat('en-NG',{style:'currency',currency,maximumFractionDigits:0}).format(value);
const hasItems=(items:unknown[]|undefined)=>Boolean(items?.length);

function EmptyCard({title,children,className='' }:{title:string;children:React.ReactNode;className?:string}){return <section className={`rounded-[28px] border border-border/50 bg-card p-5 md:p-6 shadow-soft ${className}`}><div className="flex items-center justify-between mb-5"><h2 className="font-extrabold text-ink">{title}</h2></div>{children}</section>}
function NoData({message='No orders yet — they will show up here.'}:{message?:string}){return <div className="min-h-32 flex items-center justify-center rounded-2xl border border-dashed border-border px-5 text-center text-sm text-muted-foreground">{message}</div>}
function ChartFrame({message='No orders yet — there is not enough data to chart.'}:{message?:string}){return <div className="h-56 rounded-2xl border border-dashed border-border flex items-center justify-center text-center text-sm text-muted-foreground px-5">{message}</div>}

export default function Home(){
  const [tab,setTab]=useState<Tab>('overview');
  const [ownerName,setOwnerName]=useState('');
  const {data,isLoading}=useQuery({queryKey:['dashboard'],queryFn:loadDashboard,staleTime:60000,retry:false});
  useEffect(()=>{const stored=localStorage.getItem('relay_owner_name')||auth?.currentUser?.displayName||'';setOwnerName(stored);},[]);
  const currency=data?.hero?.currency||'NGN';
  const config=useMemo(()=>({overview:{period:'Current week',label:"This Week's Revenue",value:data?.hero?.weekly,comparison:data?.hero?.weeklyComparison},monthly:{period:'Current month',label:'Total Revenue',value:data?.hero?.overview,comparison:data?.hero?.comparison},analytic:{period:'Current quarter',label:'Projected Revenue',value:data?.hero?.projected,comparison:data?.hero?.analyticComparison}}[tab]),[data,tab]);

  return <div className="h-full overflow-y-auto bg-surface-alt/30"><div className="max-w-7xl mx-auto p-4 md:p-8 pb-24">
    <div className="mb-6"><p className="text-xs font-extrabold uppercase tracking-[0.18em] text-primary">Welcome,</p><h1 className="text-3xl md:text-4xl font-extrabold tracking-tight text-ink mt-2">{ownerName||'Dashboard'}</h1></div>
    <section className="rounded-[30px] bg-ink p-6 md:p-8 text-white shadow-[0_18px_40px_rgba(22,33,62,0.22)]"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-2"><h2 className="text-lg font-extrabold">{data?.businessName||'Your business'}</h2><span className="rounded-full bg-white/10 px-3 py-1 text-xs font-bold">{config.period}</span></div><p className="mt-8 text-sm text-white/65">{config.label}</p><p className="mt-1 text-4xl md:text-5xl font-extrabold tracking-tight">{isLoading?'…':money(config.value,currency)}</p></div>{config.comparison?<div className={`rounded-full px-3 py-2 text-xs font-extrabold ${config.comparison.value>=0?'bg-lime text-ink':'bg-red-400/20 text-red-100'}`}>{config.comparison.value>=0?<ArrowUpRight size={14} className="inline"/>:<ArrowDownRight size={14} className="inline"/>} {Math.abs(config.comparison.value).toFixed(1)}% vs {config.comparison.period}</div>:<span className="rounded-full bg-white/10 px-3 py-2 text-xs font-bold text-white/65">No prior data</span>}</div></section>
    <div className="mt-5 flex gap-2 rounded-full bg-card p-1.5 w-fit border border-border/50">{(['overview','monthly','analytic'] as Tab[]).map(item=><button key={item} onClick={()=>setTab(item)} className={`rounded-full px-4 py-2 text-sm font-extrabold transition-colors ${tab===item?'bg-primary text-primary-foreground':'text-muted-foreground hover:text-foreground'}`}>{item==='overview'?'Overview':item==='monthly'?'Monthly':'Analytic'}</button>)}</div>
    {tab==='monthly'&&<div className="mt-5 grid lg:grid-cols-[minmax(0,1.55fr)_minmax(280px,.85fr)] gap-5"><div className="space-y-5"><EmptyCard title="Revenue Trend"><ChartFrame/></EmptyCard><EmptyCard title="Recent Orders"><div className="flex justify-end -mt-10 mb-4"><Link href="/orders" className="text-xs font-extrabold text-primary flex items-center">View all<ChevronRight size={14}/></Link></div>{hasItems(data?.recentOrders)?<div className="space-y-3">{data!.recentOrders!.map(order=><div key={order.id} className="flex items-center justify-between gap-3 rounded-2xl bg-muted p-3"><div><p className="font-bold text-sm">{order.customerName}</p><p className="text-xs text-muted-foreground">{order.relativeTime} · {order.itemCount} items</p></div><div className="text-right"><p className="font-extrabold text-sm">{money(order.total,currency)}</p><span className="text-[10px] font-bold uppercase text-muted-foreground">{order.status}</span></div></div>)}</div>:<NoData/>}</EmptyCard></div><div className="space-y-5"><EmptyCard title="Quick Actions"><div className="grid grid-cols-2 gap-3"><Link href="/marketing" className="rounded-2xl bg-muted p-4 hover:bg-primary/10"><Megaphone size={18}/><p className="mt-6 text-sm font-extrabold">New Campaign</p></Link><Link href="/orders" className="rounded-2xl bg-muted p-4 hover:bg-primary/10"><Package size={18}/><p className="mt-6 text-sm font-extrabold">Check Inventory</p></Link></div></EmptyCard><EmptyCard title="Needs Attention">{hasItems(data?.needsAttention)?<div className="space-y-3">{data!.needsAttention!.map(item=><Link href="/orders" key={item.id} className="flex items-center justify-between rounded-2xl bg-muted p-3"><div><p className="text-sm font-bold">{item.name}</p><p className="text-xs text-muted-foreground">{item.condition}</p></div><ChevronRight size={16}/></Link>)}</div>:<NoData message="No inventory alerts."/>}</EmptyCard></div></div>}
    {tab==='overview'&&<div className="mt-5 grid lg:grid-cols-[minmax(0,1.55fr)_minmax(280px,.85fr)] gap-5"><div className="space-y-5"><EmptyCard title="This Week's Activity"><ChartFrame message="No weekly orders yet — activity will appear here."/></EmptyCard><EmptyCard title="Top Movers This Week">{hasItems(data?.topMovers)?<div className="space-y-3">{data!.topMovers!.map(item=><div key={item.name} className="flex justify-between rounded-2xl bg-muted p-3 text-sm"><span className="font-bold">{item.name}</span><span className="text-muted-foreground">{item.orders} orders · {money(item.revenue,currency)}</span></div>)}</div>:<NoData/>}</EmptyCard></div><div className="space-y-5"><EmptyCard title="Busiest Day"><NoData message="No weekly activity yet."/></EmptyCard><EmptyCard title="Customer Mix"><NoData message="Customer mix will appear after orders arrive."/></EmptyCard></div></div>}
    {tab==='analytic'&&<div className="mt-5 grid lg:grid-cols-[minmax(0,1.55fr)_minmax(280px,.85fr)] gap-5"><div className="space-y-5"><EmptyCard title="Performance vs Target"><ChartFrame message={data?.target?'No revenue recorded for this quarter yet.':'Set a quarterly target to compare performance.'}/></EmptyCard><EmptyCard title="Top Categories">{hasItems(data?.topCategories)?<div className="space-y-4">{data!.topCategories!.map(item=><div key={item.name}><div className="flex justify-between text-sm font-bold"><span>{item.name}</span><span>{item.share}%</span></div><div className="h-2 mt-2 rounded-full bg-muted"><div className="h-full rounded-full bg-primary" style={{width:`${item.share}%`}}/></div></div>)}</div>:<NoData message="Categories will appear after paid orders."/>}</EmptyCard></div><div className="space-y-5"><EmptyCard title="Goal Progress">{data?.target?<div><p className="text-3xl font-extrabold">{Math.round((data.target.reached/data.target.value)*100)}%</p><div className="h-2 rounded-full bg-muted mt-4"><div className="h-full rounded-full bg-primary" style={{width:`${Math.min(100,(data.target.reached/data.target.value)*100)}%`}}/></div><p className="text-xs text-muted-foreground mt-3">{money(data.target.reached,currency)} of {money(data.target.value,currency)} target reached.</p></div>:<NoData message="Set a revenue target to track progress."/>}</EmptyCard><EmptyCard title="Audience Base"><NoData message="Audience segments will appear as customers arrive."/></EmptyCard><EmptyCard title="Customer LTV"><NoData message="LTV will appear after paid customer orders."/></EmptyCard></div></div>}
  </div></div>;
}
