import { useEffect, useMemo, useState } from 'react';
import { Link, useLocation, useParams } from 'wouter';
import { ArrowLeft, Check, ChevronRight, Home, Menu, Minus, Plus, Search, ShoppingBag, User, X } from 'lucide-react';
import { themes } from '@/storefront/themes';
import { readBusinessProfile } from '@/lib/business-profile';
import type { StorefrontProduct } from '@/components/storefront/StorefrontRenderer';

const SHOP_KEY='relay_shop_state_v1'; const API=import.meta.env.VITE_API_URL||'http://localhost:4000';
type CartLine={key:string;product:StorefrontProduct;qty:number;options:Record<string,string>};
type Customer={name:string;phone:string;email:string;address:string;notes:string};

const readLocal=()=>{try{return JSON.parse(localStorage.getItem(SHOP_KEY)||'{}')}catch{return {}}};
const slugify=(value:string)=>value.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');

export default function Storefront(){
  const [,navigate]=useLocation(); const {businessSlug}=useParams<{businessSlug:string}>(); const profile=readBusinessProfile(); const state=useMemo(readLocal,[]); const slug=businessSlug?.trim()||''; const [products,setProducts]=useState<StorefrontProduct[]>([]); const [store,setStore]=useState<any>(null); const [storeCategories,setStoreCategories]=useState<any[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
  const [search,setSearch]=useState(''); const [sort,setSort]=useState('popular'); const [category,setCategory]=useState(''); const [cart,setCart]=useState<CartLine[]>([]); const [customer,setCustomer]=useState<Customer>({name:'',phone:'',email:'',address:'',notes:''}); const [notice,setNotice]=useState('');
  const parts=window.location.pathname.split('/').filter(Boolean); const page=parts[2]||'home'; const param=parts[3]||''; const branding=store?.branding||{}; const baseTheme=themes.find(item=>item.id===(store?.templateId||store?.template))||themes[0]; const theme={...baseTheme,colors:{...baseTheme.colors,accent:branding.accentColor||branding.primaryColor||baseTheme.colors.accent}}; const businessName=store?.name||slug.replace(/[-_]/g,' ');
  useEffect(()=>{let alive=true;setLoading(true);setError('');fetch(`${API}/api/v1/storefronts/${encodeURIComponent(slug)}/products`).then(async response=>{if(!response.ok)throw new Error(response.status===404?'This storefront is not available yet.':'We could not load this storefront.');return response.json()}).then(payload=>{if(!alive)return;const categoryRows=payload.data.categories||[];const names=new Map(categoryRows.map((category:any)=>[category.id,category.name]));setStore(payload.data.storefront);setStoreCategories(categoryRows);setProducts((payload.data.products||[]).map((product:StorefrontProduct)=>({...product,category:product.category||names.get(product.categoryId)||product.categoryId})))}).catch(e=>alive&&setError(e instanceof Error?e.message:'We could not load this storefront. Try again.')).finally(()=>alive&&setLoading(false));return()=>{alive=false}},[slug]);
  const visible=products.filter(p=>p.availability!==false&&p.channels?.web!==false); const categories=Array.from(new Set(visible.map(p=>p.category||p.categoryId).filter(Boolean).concat(storeCategories.map(c=>c.name).filter(Boolean)))) as string[];
  const filtered=visible.filter(p=>!category||p.category===category||p.categoryId===category).filter(p=>!search||`${p.name} ${p.description||''} ${p.category||''}`.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>sort==='price'?a.price-b.price:sort==='name'?a.name.localeCompare(b.name):0);
  const total=cart.reduce((sum,line)=>sum+line.product.price*line.qty,0); const count=cart.reduce((sum,line)=>sum+line.qty,0); const path=(next:string)=>navigate(`/store/${slug}${next==='home'?'':`/${next}`}`);
  const add=(product:StorefrontProduct,options:Record<string,string>={})=>{const key=`${product.id}:${JSON.stringify(options)}`;setCart(lines=>lines.some(line=>line.key===key)?lines.map(line=>line.key===key?{...line,qty:line.qty+1}:line):[...lines,{key,product,qty:1,options}]);setNotice(`${product.name} added to cart`);setTimeout(()=>setNotice(''),1800)};
  const change=(key:string,delta:number)=>setCart(lines=>lines.map(line=>line.key===key?{...line,qty:line.qty+delta}:line).filter(line=>line.qty>0));
  const submit=async()=>{if(!customer.name||!customer.phone||!customer.address){setError('Name, phone and delivery address are required.');return}try{const sessionId=localStorage.getItem('relay_store_session')||crypto.randomUUID();localStorage.setItem('relay_store_session',sessionId);const response=await fetch(`${API}/api/v1/storefronts/${encodeURIComponent(slug)}/cart`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({sessionId,items:cart.map(line=>({productId:line.product.id,qty:line.qty}))})});if(!response.ok)throw new Error('One or more items are no longer available.');const payload=await response.json();const checkout=await fetch(`${API}/api/v1/storefronts/${encodeURIComponent(slug)}/cart/${payload.data.id}/checkout`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({customer})});if(!checkout.ok)throw new Error('Payment or checkout is unavailable right now.');setCart([]);path(`order/${(await checkout.json()).data.order.id}`)}catch(e){setError(e instanceof Error?e.message:'Checkout failed. Please try again.')}};
  if(loading)return <StorefrontFrame theme={theme} name={businessName} slug={slug}><Loading/></StorefrontFrame>;
  if(error&&!visible.length)return <StorefrontFrame theme={theme} name={businessName} slug={slug}><State title="Storefront unavailable" copy={error} action="Try again" onAction={()=>window.location.reload()}/></StorefrontFrame>;
  const current=page==='product'?visible.find(p=>p.id===param||slugify(p.name)===param):undefined;
  return <StorefrontFrame theme={theme} name={businessName} slug={slug} logo={branding.logo||store?.logo} banner={branding.banner||store?.banner} cartCount={count} onCart={()=>path('cart')} search={search} setSearch={setSearch} onHome={()=>path('home')}>
    {page==='home'&&<HomePage theme={theme} name={businessName} headline={store?.headline||`Welcome to ${businessName}`} description={store?.description||theme.tagline} categories={categories} products={visible} onCategory={value=>{setCategory(value);path('shop')}} onProduct={p=>path(`product/${p.id}`)} onShop={()=>path('shop')}/>} 
    {page==='shop'&&<ShopPage products={filtered} categories={categories} category={category} setCategory={setCategory} search={search} sort={sort} setSort={setSort} add={add} open={p=>path(`product/${p.id}`)}/>} 
    {page==='category'&&<ShopPage products={filtered} categories={categories} category={param} setCategory={value=>path(`category/${slugify(value)}`)} search={search} sort={sort} setSort={setSort} add={add} open={p=>path(`product/${p.id}`)}/>} 
    {page==='product'&&(current?<ProductPage product={current} add={add} onBack={()=>path('shop')}/>:<State title="Product unavailable" copy="This product may have been removed or unpublished." action="Back to shop" onAction={()=>path('shop')}/>) }
    {page==='cart'&&<CartPage cart={cart} total={total} change={change} onShop={()=>path('shop')} onCheckout={()=>path('checkout')}/>} 
    {page==='checkout'&&<Checkout customer={customer} setCustomer={setCustomer} total={total} submit={submit} error={error} onBack={()=>path('cart')}/>} 
    {page==='order'&&<Confirmation id={param} onShop={()=>path('shop')}/>} 
    {page==='about'&&<About profile={profile} name={businessName}/>} 
    {notice&&<div className="fixed bottom-5 left-1/2 z-50 -translate-x-1/2 rounded-full bg-ink px-4 py-2 text-sm font-bold text-white">{notice}</div>}
  </StorefrontFrame>;
}

function StorefrontFrame({theme,name,slug,logo,banner,children,cartCount,onCart,search,setSearch,onHome}:{theme:any;name:string;slug:string;logo?:string;banner?:string;children:any;cartCount?:number;onCart?:()=>void;search?:string;setSearch?:(v:string)=>void;onHome?:()=>void}){return <main className="min-h-screen" style={{background:theme.colors.bg,color:theme.colors.ink,fontFamily:theme.fonts.body}}><header className="sticky top-0 z-20 border-b backdrop-blur" style={{background:theme.colors.bg,borderColor:theme.colors.border}}><div className="mx-auto flex max-w-6xl items-center gap-3 px-5 py-4"><button onClick={onHome} className="flex items-center gap-2 text-lg font-extrabold" style={{fontFamily:theme.fonts.heading}}>{logo&&<img src={logo} alt="" className="h-8 w-8 rounded-lg object-cover"/>}{name}</button><nav className="ml-auto hidden gap-5 text-sm font-bold sm:flex"><button onClick={onHome}>Home</button><Link href={`/store/${slug}/shop`}>Shop</Link><Link href={`/store/${slug}/about`}>About</Link></nav><button onClick={onCart} className="relative rounded-xl p-2" style={{background:theme.colors.accent,color:theme.colors.accentInk}}><ShoppingBag size={18}/>{cartCount? <span className="absolute -right-2 -top-2 rounded-full bg-ink px-1.5 text-[10px] text-white">{cartCount}</span>:null}</button></div>{banner&&<img src={banner} alt="" className="h-24 w-full object-cover"/>}{setSearch&&<div className="mx-auto max-w-6xl px-5 pb-3"><div className="flex items-center gap-2 rounded-xl border px-3 py-2" style={{borderColor:theme.colors.border}}><Search size={16}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search products" className="w-full bg-transparent text-sm outline-none"/></div></div>}</header><div>{children}</div><footer className="mx-auto max-w-6xl px-5 py-10 text-sm opacity-60"><p>{name}</p><p className="mt-1">Powered by Relay commerce</p></footer></main>}
function HomePage({theme,name,headline,description,categories,products,onCategory,onProduct,onShop}:any){return <><section className="mx-auto max-w-6xl px-5 pb-10 pt-14 sm:pt-24"><p className="text-xs font-bold uppercase tracking-[.18em] opacity-60">{theme.name}</p><h1 className="mt-3 max-w-3xl text-4xl font-extrabold leading-tight sm:text-6xl" style={{fontFamily:theme.fonts.heading}}>{headline}</h1><p className="mt-4 max-w-2xl leading-7 opacity-70">{description}</p><button onClick={onShop} className="mt-6 rounded-xl px-5 py-3 text-sm font-extrabold" style={{background:theme.colors.accent,color:theme.colors.accentInk}}>Shop now</button></section><section className="mx-auto max-w-6xl px-5 pb-10"><h2 className="text-xl font-extrabold">Browse categories</h2><div className="mt-4 flex gap-2 overflow-x-auto">{categories.map((cat:string)=><button key={cat} onClick={()=>onCategory(cat)} className="shrink-0 rounded-full border px-4 py-2 text-sm font-bold" style={{borderColor:theme.colors.border}}>{cat}</button>)}</div></section><section className="mx-auto max-w-6xl px-5 pb-16"><div className="flex items-center justify-between"><h2 className="text-xl font-extrabold">Featured products</h2><button onClick={onShop} className="text-sm font-bold opacity-60">View all</button></div><div className="mt-4 grid grid-cols-2 gap-4 sm:grid-cols-4">{products.slice(0,4).map((p:StorefrontProduct)=><ProductCard key={p.id} product={p} add={()=>onProduct(p)} theme={theme}/>)}</div></section></>}
function ShopPage({products,categories,category,setCategory,search,sort,setSort,add,open}:any){return <section className="mx-auto max-w-6xl px-5 py-10"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm opacity-60">{search?`Results for “${search}”`:category||'All products'}</p><h1 className="text-3xl font-extrabold">Shop</h1></div><select value={sort} onChange={e=>setSort(e.target.value)} className="rounded-xl border bg-transparent px-3 py-2 text-sm"><option value="popular">Popular</option><option value="price">Price</option><option value="name">Name</option></select></div><div className="mt-5 flex gap-2 overflow-x-auto pb-2"><button onClick={()=>setCategory('')} className="shrink-0 rounded-full px-3 py-2 text-xs font-bold">All</button>{categories.map((cat:string)=><button key={cat} onClick={()=>setCategory(cat)} className="shrink-0 rounded-full px-3 py-2 text-xs font-bold">{cat}</button>)}</div>{products.length?<div className="mt-5 grid grid-cols-2 gap-4 sm:grid-cols-3 lg:grid-cols-4">{products.map((p:StorefrontProduct)=><ProductCard key={p.id} product={p} add={()=>add(p)} open={()=>open(p)}/>)}</div>:<State title="Nothing here yet" copy="Try another category or search term."/>}</section>}
function ProductCard({product,add,open,theme}:any){return <article className="overflow-hidden rounded-2xl border" style={{borderColor:theme?.colors.border}}><button onClick={open||add} className="block w-full text-left"><div className="aspect-square bg-muted">{(product.images?.[0]||product.image)&&<img src={product.images?.[0]||product.image} alt={product.name} className="h-full w-full object-cover"/>}</div><div className="p-3"><h3 className="font-bold">{product.name}</h3><p className="mt-1 text-sm opacity-65">₦{Number(product.price).toLocaleString('en-NG')}</p></div></button>{add&&<button onClick={add} className="m-3 mt-0 rounded-lg bg-ink px-3 py-2 text-xs font-bold text-white">Quick add</button>}</article>}
function ProductPage({product,add,onBack}:any){const [qty,setQty]=useState(1);return <section className="mx-auto max-w-4xl px-5 py-10"><button onClick={onBack} className="mb-6 flex items-center gap-2 text-sm font-bold opacity-60"><ArrowLeft size={16}/> Back to shop</button><div className="grid gap-8 md:grid-cols-2"><div className="aspect-square rounded-3xl bg-muted">{(product.images?.[0]||product.image)&&<img src={product.images?.[0]||product.image} alt={product.name} className="h-full w-full rounded-3xl object-cover"/>}</div><div><h1 className="text-3xl font-extrabold">{product.name}</h1><p className="mt-3 text-xl font-bold">₦{Number(product.price).toLocaleString('en-NG')}</p><p className="mt-5 leading-7 opacity-70">{product.description||'Available to order.'}</p><div className="mt-6 flex items-center gap-3"><button onClick={()=>setQty(Math.max(1,qty-1))} className="rounded-lg border p-2"><Minus size={16}/></button><span className="w-6 text-center font-bold">{qty}</span><button onClick={()=>setQty(qty+1)} className="rounded-lg border p-2"><Plus size={16}/></button></div><button onClick={()=>{for(let i=0;i<qty;i++)add(product)}} className="mt-5 w-full rounded-xl bg-ink px-4 py-3 font-extrabold text-white">Add to cart</button></div></div></section>}
function CartPage({cart,total,change,onShop,onCheckout}:any){return <section className="mx-auto max-w-3xl px-5 py-10"><h1 className="text-3xl font-extrabold">Your cart</h1>{cart.length?<><div className="mt-6 space-y-3">{cart.map((line:CartLine)=><div key={line.key} className="flex items-center gap-3 rounded-xl border p-3"><div className="min-w-0 flex-1"><p className="font-bold">{line.product.name}</p><p className="text-sm opacity-60">₦{(line.product.price*line.qty).toLocaleString('en-NG')}</p></div><button onClick={()=>change(line.key,-1)}><Minus size={15}/></button><span>{line.qty}</span><button onClick={()=>change(line.key,1)}><Plus size={15}/></button></div>)}</div><div className="mt-6 flex justify-between border-t pt-4 text-lg font-extrabold"><span>Total</span><span>₦{total.toLocaleString('en-NG')}</span></div><div className="mt-5 flex gap-2"><button onClick={onShop} className="flex-1 rounded-xl border px-4 py-3 font-bold">Continue shopping</button><button onClick={onCheckout} className="flex-1 rounded-xl bg-ink px-4 py-3 font-bold text-white">Checkout</button></div></>:<State title="Your cart is empty" copy="Add something from the shop to get started." action="Browse shop" onAction={onShop}/>}</section>}
function Checkout({customer,setCustomer,total,submit,error,onBack}:any){return <section className="mx-auto max-w-lg px-5 py-10"><button onClick={onBack} className="mb-5 flex items-center gap-2 text-sm font-bold opacity-60"><ArrowLeft size={16}/> Back to cart</button><h1 className="text-3xl font-extrabold">Checkout</h1><div className="mt-6 grid gap-3">{(['name','phone','email','address','notes'] as const).map(field=><input key={field} value={customer[field]} onChange={e=>setCustomer({...customer,[field]:e.target.value})} placeholder={field==='name'?'Full name':field==='phone'?'Phone number':field==='email'?'Email (optional)':field==='address'?'Delivery address':'Delivery instructions (optional)'} className="rounded-xl border bg-transparent px-3 py-3"/>)}{error&&<p className="text-sm font-bold text-red-600">{error}</p>}<div className="mt-3 flex justify-between text-lg font-extrabold"><span>Total</span><span>₦{total.toLocaleString('en-NG')}</span></div><button onClick={submit} className="rounded-xl bg-ink px-4 py-3 font-extrabold text-white">Place order</button><p className="text-xs opacity-60">Payment is completed through the configured business payment provider.</p></div></section>}
function Confirmation({id,onShop}:any){return <section className="mx-auto max-w-lg px-5 py-20 text-center"><Check className="mx-auto" size={48}/><h1 className="mt-5 text-3xl font-extrabold">Order received</h1><p className="mt-2 opacity-70">Reference: {id}</p><button onClick={onShop} className="mt-7 rounded-xl bg-ink px-5 py-3 font-bold text-white">Continue shopping</button></section>}
function About({profile,name}:any){return <section className="mx-auto max-w-3xl px-5 py-12"><h1 className="text-4xl font-extrabold">About {name}</h1><p className="mt-5 leading-8 opacity-70">{profile?.description||'Learn more about this business.'}</p>{profile?.address&&<p className="mt-5 font-bold">{profile.address}</p>}</section>}
function Loading(){return <div className="mx-auto max-w-6xl animate-pulse px-5 py-20"><div className="h-5 w-32 rounded bg-muted"/><div className="mt-5 h-16 max-w-xl rounded bg-muted"/><div className="mt-10 grid grid-cols-2 gap-4 sm:grid-cols-4">{[1,2,3,4].map(item=><div key={item} className="aspect-square rounded-2xl bg-muted"/>)}</div></div>}
function State({title,copy,action,onAction}:any){return <div className="mx-auto max-w-xl px-5 py-24 text-center"><h1 className="text-2xl font-extrabold">{title}</h1><p className="mt-2 opacity-65">{copy}</p>{action&&<button onClick={onAction} className="mt-5 rounded-xl bg-ink px-4 py-3 font-bold text-white">{action}</button>}</div>}
