import {ArrowRight,Check} from 'lucide-react';
import {Link} from 'wouter';
import {businessInitials,readBusinessProfile} from '@/lib/business-profile';

const confetti=Array.from({length:36},(_,index)=>({left:`${(index*29)%100}%`,delay:`${(index%9)*110}ms`,color:['#b8f34b','#ff8a65','#7dd3fc','#c4b5fd','#f9d65c'][index%5],size:6+(index%4)*3}));

export default function SetupComplete(){
  const profile=readBusinessProfile();
  const businessName=profile?.businessName||'your business';
  return <div className="relative min-h-[100dvh] overflow-hidden bg-surface-alt/40 px-5 py-8 text-ink flex items-center justify-center"><style>{`@keyframes relay-confetti{0%{transform:translate3d(0,-12vh,0) rotate(0deg);opacity:0}12%{opacity:1}100%{transform:translate3d(30px,110vh,0) rotate(680deg);opacity:0}}@media (prefers-reduced-motion:reduce){.relay-confetti{animation:none!important;display:none}}`}</style>{confetti.map((piece,index)=><span key={index} className="relay-confetti absolute top-0 rounded-sm" style={{left:piece.left,width:piece.size,height:piece.size*1.5,backgroundColor:piece.color,animation:`relay-confetti ${1800+(index%5)*240}ms cubic-bezier(.2,.7,.3,1) ${piece.delay} forwards`}}/>)}<main className="relative z-10 w-full max-w-lg rounded-[32px] border border-border/60 bg-card p-7 text-center shadow-[0_24px_60px_rgba(22,33,62,0.16)] md:p-10"><div className="mx-auto flex h-20 w-20 items-center justify-center overflow-hidden rounded-[24px] bg-lime text-ink shadow-[0_12px_28px_rgba(126,211,33,0.35)]">{profile?.logo?<img src={profile.logo} alt={`${businessName} logo`} className="h-full w-full object-cover"/>:<span className="text-2xl font-extrabold">{businessInitials(businessName)}</span>}</div><div className="mx-auto mt-6 flex h-8 w-8 items-center justify-center rounded-full bg-lime-pale text-ink"><Check size={18}/></div><p className="mt-5 text-xs font-extrabold uppercase tracking-[0.18em] text-primary">Setup complete</p><h1 className="mt-2 text-3xl font-extrabold tracking-tight md:text-4xl">Congratulations!</h1><p className="mx-auto mt-4 max-w-sm text-sm leading-6 text-muted-foreground">{businessName} is ready to go. Your business details, branding, and setup choices are now saved to your account.</p><Link href="/dashboard" className="mt-8 inline-flex items-center gap-2 rounded-xl bg-ink px-5 py-3 text-sm font-extrabold text-white transition-opacity hover:opacity-90">Go to dashboard <ArrowRight size={16}/></Link></main></div>;
}
